services:
  - type: static
    name: flux-platform-frontend
    env: static
    rootDir: .
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    publishPath: ./dist # Aponta para a pasta de build est√°tico
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
